# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.vm.hostname = "elk.xtl"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "elk.xtl"
     vb.cpus = 2
     vb.memory = "2048"
  end
   
  # config.vm.provision "shell", path: "./../install-docker-kube.sh"

  config.vm.provision "shell", inline: <<-SHELL
    echo "root password"
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd


cat >>/etc/hosts<<EOF
# 172.16.10.105 elk.xtl
EOF

    
  SHELL
end